- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: install docker
      shell: >
        apt-get update && \
        apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
        apt-key fingerprint 0EBFCD88 && \
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
        apt-get update && \
        apt-get install -y docker-ce docker-ce-cli containerd.io
      tags: docker

    - name: install python3 & pip
      apt:
        name: [python-apt, python3, python3-pip]
        update_cache: yes
        state: present
      tags: pip
      
    - name: install necessary python modules
      pip:
        name:
          - docker
      tags: pip