- hosts: kibana
  become: yes
  tasks:

    - name: create kibana config dir
      file: path={{ kibana_config_dir }} state=directory

    - name: docker pull
      docker_image: name={{ kibana_image }} state=present

    - name: copy systemd file
      template: src=kibana.service.j2 dest=/etc/systemd/system/{{ kibana_service_name }}.service
      register: systemd_changed

    - name: copy kibana.yml
      template: src=kibana.yml.j2 dest={{ kibana_config_dir }}/kibana.yml

    - name: reload systemd
      shell: systemctl daemon-reload

    - name: start/restart service
      service: name={{ kibana_service_name }} state=restarted